//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aufgabe
    {
        public Aufgabe()
        {
            this.Raumschiffe = new HashSet<Raumschiff>();
        }
    
        public int ID { get; set; }
        public string Aufgabenbeschreibung { get; set; }
    
        public virtual ICollection<Raumschiff> Raumschiffe { get; set; }
    }
}
