//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class Himmelskoerper
    {
        public Himmelskoerper()
        {
            this.UrlSammlungen = new HashSet<UrlSammlung>();
            this.TrabantenUmlaufbahnen = new HashSet<Umlaufbahn>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public double Masse_in_kg { get; set; }
        public int HimmelskoerperTyp_ID { get; set; }
        public Nullable<int> SpektralklasseId { get; set; }
    
        public virtual Raumschiff RaumschiffeTab { get; set; }
        public virtual Sterne_Planeten_Monde Sterne_Planeten_MondeTab { get; set; }
        public virtual HimmelskoerperTyp HimmelskoerperTyp { get; set; }
        public virtual ICollection<UrlSammlung> UrlSammlungen { get; set; }
        public virtual Umlaufbahn Umlaufbahn { get; set; }
        public virtual ICollection<Umlaufbahn> TrabantenUmlaufbahnen { get; set; }
        public virtual Bild Bild { get; set; }
        public virtual Spektralklasse Spektralklasse { get; set; }
    }
}
