//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class HimmelskoerperTyp
    {
        public HimmelskoerperTyp()
        {
            this.Himmelskoerper = new HashSet<Himmelskoerper>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Himmelskoerper> Himmelskoerper { get; set; }
    }
}
