//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raumschiff
    {
        public Raumschiff()
        {
            this.Aufgaben = new HashSet<Aufgabe>();
        }
    
        public System.DateTime Start_der_Mission { get; set; }
        public int HimmelskoerperID { get; set; }
        public int Land_ID { get; set; }
        public int RaumschiffAufgaben_ID { get; set; }
    
        public virtual Himmelskoerper Himmelskoerper { get; set; }
        public virtual Land Land { get; set; }
        public virtual ICollection<Aufgabe> Aufgaben { get; set; }
    }
}
