//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sterne_Planeten_Monde
    {
        public double Aequatordurchmesser_in_km { get; set; }
        public double Polardurchmesser_in_km { get; set; }
        public double Oberflaechentemperatur_in_K { get; set; }
        public double Rotationsperiode_in_Stunden { get; set; }
        public double Fallbeschleunigung_in_meter_pro_sec { get; set; }
        public double Rotationsachsenneigung_in_Grad { get; set; }
        public int HimmelskoerperID { get; set; }
        public double Leuchtkraft_in_Lsonne { get; set; }
    
        public virtual Himmelskoerper Himmelskoerper { get; set; }
    }
}
