//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlSammlung
    {
        public int ID { get; set; }
        public string Kurzbeschreibung { get; set; }
        public string Url { get; set; }
        public EnumUrlTypen UrlTyp { get; set; }
        public int Himmelskoerper_ID { get; set; }
    
        public virtual Himmelskoerper Himmelskoerper { get; set; }
    }
}
