//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI.MVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeplerBI.MVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Längenbereich End- Parameter ist ungültig.
        /// </summary>
        internal static string CfgLengthRangeFlt_View_end_param_invalid {
            get {
                return ResourceManager.GetString("CfgLengthRangeFlt_View_end_param_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Längenbereich Begin- Parameter ist ungültig.
        /// </summary>
        internal static string fgLengthRangeFlt_View_begin_param_invalid {
            get {
                return ResourceManager.GetString("fgLengthRangeFlt_View_begin_param_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der darzustellenden RPN- Term muss mit eine Funktion sein.
        /// </summary>
        internal static string Models_Filters_ConfigData_rpn_function_functionname_token_missing {
            get {
                return ResourceManager.GetString("Models_Filters_ConfigData_rpn_function_functionname_token_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Parameterliste der RPN Funktion {0:s} ist ungültig.
        /// </summary>
        internal static string Models_Filters_ConfigData_rpn_function_invalid_paramlist {
            get {
                return ResourceManager.GetString("Models_Filters_ConfigData_rpn_function_invalid_paramlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der RPN- Term Parameter der Action enthält nicht das erfolderliche Configcol Kommando.
        /// </summary>
        internal static string PN_ConfigCol_required {
            get {
                return ResourceManager.GetString("PN_ConfigCol_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PN- Term in URL konnte nicht korrekt geparst werden:.
        /// </summary>
        internal static string PNParseFailed {
            get {
                return ResourceManager.GetString("PNParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf dem Stapel gibt es nach dem erfolgreichen Parsen Objekte, deren Typ verschieden von ConfigDataToken ist..
        /// </summary>
        internal static string PNParseFailed_StackInconsistent {
            get {
                return ResourceManager.GetString("PNParseFailed_StackInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Range- Filter erwartet genau zwei Parameter (begin, end).
        /// </summary>
        internal static string RpnRngFlt_ParameterCount_2_expected {
            get {
                return ResourceManager.GetString("RpnRngFlt_ParameterCount_2_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als fSubTree wurde ein Rangefilter erwartet.
        /// </summary>
        internal static string SubtreeAsRangeFlt_expected {
            get {
                return ResourceManager.GetString("SubtreeAsRangeFlt_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als fSubTree wurde ein Sortfilter erwartet.
        /// </summary>
        internal static string SubtreeAsSortFlt_expected {
            get {
                return ResourceManager.GetString("SubtreeAsSortFlt_expected", resourceCulture);
            }
        }
    }
}
